name: artifact-test

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  upload-a:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy files
        run: |
          mkdir -p target/debug
          dd if=/dev/urandom of=target/debug/binary-a bs=1M count=10

      - name: Upload artifact-a
        uses: actions/upload-artifact@v4
        with:
          name: artifact-a
          if-no-files-found: error
          path: |
            target/debug/binary-a

  upload-b:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy files
        run: |
          mkdir -p target/debug
          dd if=/dev/urandom of=target/debug/binary-b bs=1M count=10

      - name: Upload artifact-b
        uses: actions/upload-artifact@v4
        with:
          name: artifact-b
          if-no-files-found: error
          path: |
            target/debug/binary-b

  upload-c:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy files
        run: |
          mkdir -p target/debug
          dd if=/dev/urandom of=target/debug/binary-c bs=1M count=10

      - name: Upload artifact-c
        uses: actions/upload-artifact@v4
        with:
          name: artifact-c
          if-no-files-found: error
          path: |
            target/debug/binary-c

  download-one-v4:
    needs: [upload-a, upload-b, upload-c]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact-b with v4 (selective)
        uses: actions/download-artifact@v4
        with:
          name: artifact-b

      - name: Verify
        run: ls -lahR .

  download-all-v4:
    needs: [upload-a, upload-b, upload-c]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts with v4
        uses: actions/download-artifact@v4

      - name: Verify
        run: ls -lahR .

  download-one-v5:
    needs: [upload-a, upload-b, upload-c]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact-b with v5 (selective)
        uses: actions/download-artifact@v5
        with:
          name: artifact-b

      - name: Verify
        run: ls -lahR .
